FROM nginx:alpine
RUN rm -f /etc/nginx/conf.d/default.conf
COPY docuShare.conf /etc/nginx/conf.d/
COPY nginx-selfsigned.crt /etc/nginx/ssl/
COPY nginx-selfsigned.key /etc/nginx/ssl/
COPY resources/ /usr/share/nginx/resources
